general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = /home/gip/.cache/current_wallpaper
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 3 # 0 disables blurring
    blur_size = 7
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(30, 30, 46, 0.5) # Catppuccin Mocha Base with transparency
    font_color = rgb(205, 214, 244)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -130
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(205, 214, 244)
    font_size = 120
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 60
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi there, $USER
    color = rgb(205, 214, 244)
    font_size = 25
    font_family = JetBrainsMono Nerd Font
    position = 0, -40
    halign = center
    valign = center
}

# Battery Label
label {
    monitor =
    text = cmd[update:1000] echo "<b>$(cat /sys/class/power_supply/BAT0/capacity)%</b>"
    color = rgba(166, 227, 161, 1.0) # Catppuccin Green
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, -80
    halign = center
    valign = center
}

# Optional: Add a "Charging" icon if plugged in
label {
    monitor =
    text = cmd[update:1000] echo "$(cat /sys/class/power_supply/AC0/online | sed 's/1/󱐋/; s/0//')"
    color = rgba(249, 226, 175, 1.0) # Catppuccin Yellow
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 45, -80
    halign = center
    valign = center
}
