---@diagnostic disable: undefined-global
-- #######################################################################################
-- AUTOGENERATED HYPRLAND CONFIG.
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

--###############
--## MONITORS ###
--###############

-- See https://wiki.hypr.land/Configuring/Monitors/
-- monitor=,preferred,auto,auto
-- monitor = eDP-1,2880x1800@90,0x0,1.5
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
	output = "eDP-1",
	mode = "2880x1800@60",
	position = "0x0",
	scale = "1.5",
})

-- monitor = HDMI-A-1,1920x1080@144,480x-1080,1 #kosan
-- monitor = HDMI-A-1,1920x1080@144,0x-1080,1 #kosan
hl.monitor({
	output = "HDMI-A-1",
	mode = "1920x1080@75",
	position = "1920x0",
	scale = "1",
})

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use
local terminal = "kitty"
local fileManager = "dolphin"
local menu = "hyprlauncher"

--################
--## AUTOSTART ###
--################

-- --- SYSTEM & ENVIRONMENT DAEMONS ---
-- Import Hyprland environment into DBus/systemd for screen sharing & portals

-- Force GTK/Qt applications to default to Dark Theme

-- --- UI & NOTIFICATIONS ---

-- --- WALLPAPER DAEMON ---
-- Chain daemon startup with restore to prevent race conditions (use swww or awww)

-- --- CLIPBOARD MANAGER ---
-- Monitor text and image buffers with capped item limits

-- rclone gdrive
-- exec-once = rclone mount gdrive-work: ~/Gdrive/work --vfs-cache-mode full --vfs-cache-max-age 24h --vfs-write-back 5s --daemon

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Dual GPU setup
hl.env("AQ_DRM_DEVICES", "/dev/dri/card2:/dev/dri/card1")

-- Desktop integration
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("GDK_BACKEND", "wayland,x11")

-- --- UNIFIED QT WAYLAND SCALING ---
-- Force Qt5 and Qt6 to use native Wayland protocols
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- Let Hyprland compositor handle scaling naturally for Qt apps
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "0")
hl.env("QT_SCALE_FACTOR_ROUNDING_POLICY", "PassThrough")

-- Prevent Qt from forcing desktop-DPI multiplier on top of Wayland
hl.env("QT_ENABLE_HIGHDPI_SCALING", "0")
hl.env("QT_SCALE_FACTOR", "1")

-- Browser Wayland support
hl.env("MOZ_ENABLE_WAYLAND", "1")

-- trying new scaling settings
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

hl.config({
	cursor = {
		no_hardware_cursors = 2,
		enable_hyprcursor = true,
	},
})

--##################
--## PERMISSIONS ###
--##################

-- See https://wiki.hypr.land/Configuring/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- ecosystem {
--   enforce_permissions = 1
-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow
-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################
--## LOOK AND FEEL ###
--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
	general = {
		-- perfect
		-- gaps_in = 2
		-- gaps_out = 2, 3, 3, 3
		gaps_in = 3,
		gaps_out = { top = 3, right = 4, bottom = 4, left = 4 },
		border_size = 2,
		-- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
		-- default colors
		-- col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
		-- col.inactive_border = rgba(595959aa)
		--sazabi color
		col = {
			active_border = { colors = { "rgba(f38ba8ee)", "rgba(fab387ee)" }, angle = 45 },
			inactive_border = "rgba(181825aa)",
		},
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,
		-- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "dwindle",
	},
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
	decoration = {
		-- rounding = 5
		rounding = 6,
		rounding_power = 2,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 0.95,
		-- shadow {
		--     enabled = true
		--     range = 4
		--     render_power = 3
		--     color = rgba(1a1a1aee)
		-- }
		shadow = {
			enabled = false, -- Try this if it still feels 'heavy'
		},
		-- https://wiki.hypr.land/Configuring/Variables/#blur
		-- blur {
		--     enabled = true
		--     size = 3
		--     passes = 1
		--
		--     vibrancy = 0.1696
		-- }
		--
		blur = {
			enabled = false,
		},
	},
})

-- New syntax for Waybar blur
hl.layer_rule({
	match = { namespace = "waybar" },
	blur = false,
})

hl.layer_rule({
	match = { namespace = "waybar" },
	ignore_alpha = 0.1,
})

-- Hyprland now uses 'animation' as a layerrule instead of 'transition'
hl.layer_rule({
	match = { namespace = "waybar" },
	animation = "fade",
})

-- https://wiki.hypr.land/Configuring/Variables/#animations
hl.config({
	animations = {
		enabled = true,
		-- This curve starts fast but settles much more "linearly" at the end
		-- It avoids the long "trailing" slow-motion effect
	},
})

hl.curve("snap", { type = "bezier", points = { { 0.1, 1 }, { 0.3, 1 } } })
hl.animation({
	leaf = "windows",
	enabled = true,
	speed = 2,
	bezier = "snap",
	style = "slide",
})
hl.animation({
	leaf = "workspaces",
	enabled = true,
	speed = 3,
	bezier = "snap",
	style = "slide",
})
hl.animation({
	leaf = "windowsOut",
	enabled = true,
	speed = 2,
	bezier = "snap",
	style = "popin 80%",
})
hl.animation({
	leaf = "fade",
	enabled = true,
	speed = 2,
	bezier = "snap",
})

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- workspace = w[tv1], gapsout:0, gapsin:0
-- workspace = f[1], gapsout:0, gapsin:0
-- windowrule {
--     name = no-gaps-wtv1
--     match:float = false
--     match:workspace = w[tv1]
--
--     border_size = 0
--     rounding = 0
-- }
-- ==========================================
-- ✨ SMART GAPS (Dynamic Windows Rules)
-- ==========================================

-- When there is only 1 visible tiled window (w[tv1]), bump gaps up to 10
-- workspace = w[tv1], gapsout:8 30 16 30, gapsin:10, rounding:10
hl.window_rule({
	name = "single-window-rounding",
	match = {
		float = false,
		workspace = "w[tv1]",
	},
	rounding = 5,
})

hl.window_rule({
	name = "multi-window-rounding",
	match = {
		float = false,
		workspace = "w[tv2-99]",
	},
	rounding = 5,
})

-- When an app is truly fullscreen (f[1]), remove all gaps completely
-- workspace = f[1], gapsout:0, gapsin:0
--
-- windowrule {
--     name = no-gaps-f1
--     match:float = false
--     match:workspace = f[1]
--
--     border_size = 0
--     rounding = 0
-- }

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
	dwindle = {
		-- pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
		preserve_split = true, -- You probably want this
	},
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
	master = {
		new_status = "master",
	},
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
	misc = {
		force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
		-- vfr = false
		-- Add this line here to disable drag smoothing:
		animate_mouse_windowdragging = false,
	},
})

--############
--## INPUT ###
--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		follow_mouse = 1,
		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
		touchpad = {
			natural_scroll = true,
			scroll_factor = 0.5,
		},
	},
})

-- See https://wiki.hypr.land/Configuring/Gestures
hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

--##################
--## KEYBINDINGS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/
local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- --- ESSENTIAL APPS & LAUNCHERS ---
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + W", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd('xdg-open "https://"'))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("obsidian"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("~/.config/rofi/launchers/type-6/launcher.sh"))
hl.bind(
	mainMod .. " + PERIOD",
	hl.dsp.exec_cmd(
		'rofimoji --action copy --selector-args "-theme ~/.config/rofi/emoji.rasi" && sleep 0.1 && wtype -M ctrl v'
	)
)
hl.bind(
	mainMod .. " + V",
	hl.dsp.exec_cmd(
		"cliphist list | rofi -dmenu -theme ~/.config/rofi/launchers/type-6/style-1.rasi | cliphist decode | wl-copy && wtype -M ctrl v"
	)
)
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))

hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("swaync-client -t -sw"))

-- --- SESSION & POWER CONTROLS ---
-- Manual Lock (Prevents fat-fingering $mainMod + Left arrow)
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd("loginctl lock-session"))

-- Power Menu (wlogout)
hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd("pkill wlogout || wlogout"))
hl.bind(
	mainMod .. " + M",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit")
)

-- --- WINDOW MANAGEMENT & LAYOUTS ---
-- Cleaned Floating/Fullscreen toggles (No more overlapping $mainMod + F actions)
-- bind = $mainMod, F, togglefloating,
-- # Toggle floating AND immediately resize to 1600x1000 + center on screen

-- hl.bind(mainMod .. " + F", function()
-- 	hl.dispatch(hl.dsp.window.float({ action = "toggle" }))
-- 	hl.dispatch(hl.dsp.window.resize({ x = 1600, y = 1000, relative = false }))
-- end)
hl.bind(mainMod .. " + F", function()
	hl.dispatch(hl.dsp.window.float({ action = "toggle" }))
	hl.dispatch(hl.dsp.window.resize({ x = 1600, y = 1000, relative = false }))
	hl.timer(function()
		hl.dispatch(hl.dsp.exec_raw("exec hyprctl dispatch centerwindow"))
	end, { timeout = 50, type = "oneshot" })
end)

hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainMod .. " + C", hl.dsp.window.center())

hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind("SUPER + SHIFT + X", hl.dsp.layout("swapsplit"))

-- Move focus (Arrow keys)
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Swap windows (Shift + Arrow keys)
hl.bind("SUPER + SHIFT + left", hl.dsp.window.swap({ direction = "l" }))
hl.bind("SUPER + SHIFT + right", hl.dsp.window.swap({ direction = "r" }))
hl.bind("SUPER + SHIFT + up", hl.dsp.window.swap({ direction = "u" }))
hl.bind("SUPER + SHIFT + down", hl.dsp.window.swap({ direction = "d" }))

-- Window Resizing
hl.bind(mainMod .. " + EQUAL", hl.dsp.window.resize({ x = 40, y = 40, relative = true }), { repeating = true })
hl.bind(mainMod .. " + MINUS", hl.dsp.window.resize({ x = -40, y = -40, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + EQUAL", hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + MINUS", hl.dsp.window.resize({ x = 0, y = 40, relative = true }), { repeating = true })

-- --- WORKSPACES & SCRATCHPADS ---
-- Switch workspaces 1-10
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move window to workspace 1-10
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- General Scratchpad
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Dedicated Tmux Scratchpad
hl.workspace_rule({
	workspace = "special:scratchpad",
	on_created_empty = "kitty tmux",
})

hl.bind(mainMod .. " + T", hl.dsp.workspace.toggle_special("scratchpad"))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.window.move({ workspace = "special:scratchpad" }))

-- Mouse bindings
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

-- --- HARDWARE & SYSTEM SCRIPTS ---
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("~/.config/hypr/scripts/wbrestart.sh"))
hl.bind("SUPER + F11", hl.dsp.exec_cmd("~/.config/hypr/scripts/hz_cycle.sh"))
hl.bind(
	mainMod .. " + F12",
	hl.dsp.exec_cmd(
		'asusctl profile next && notify-send "ASUS Profile" "$(asusctl profile get | grep \'Active profile\')" -i diagnostic'
	)
)

-- Media / Brightness / Volume (SwayOSD & Playerctl)
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("swayosd-client --output-volume raise"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("swayosd-client --output-volume lower"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86MonBrightnessUp",
	hl.dsp.exec_cmd("swayosd-client --brightness raise"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86MonBrightnessDown",
	hl.dsp.exec_cmd("swayosd-client --brightness lower"),
	{ locked = true, repeating = true }
)

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- --- MONITOR WORKSPACE ASSIGNMENTS ---
hl.workspace_rule({
	workspace = "1",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "2",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "3",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "4",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "5",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "6",
	monitor = "HDMI-A-1",
	default = true,
})

hl.workspace_rule({
	workspace = "7",
	monitor = "HDMI-A-1",
})

hl.workspace_rule({
	workspace = "8",
	monitor = "HDMI-A-1",
})

hl.workspace_rule({
	workspace = "9",
	monitor = "HDMI-A-1",
})

hl.workspace_rule({
	workspace = "10",
	monitor = "HDMI-A-1",
})

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrules that are useful

hl.window_rule({
	name = "suppress-maximize-events",
	match = {
		class = ".*",
	},
	-- Ignore maximize requests from all apps. You'll probably like this.
	suppress_event = "maximize",
})

hl.window_rule({
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},
	-- Fix some dragging issues with XWayland
	no_focus = true,
})

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",
	match = {
		class = "hyprland-run",
	},
	move = "20 monitor_h-120",
	float = true,
})

hl.window_rule({
	name = "firefox-pip",
	match = {
		class = "^(firefox)$",
		title = "^Picture-in-Picture$",
	},
	-- Match props
	-- Effects
	float = true,
	pin = true,
	animation = "none",
	size = "530 300",
	-- move = 1385 895
	move = "1380 830",
})

hl.window_rule({
	name = "brave-youtube-pip",
	match = {
		title = "^Picture in picture$",
	},
	-- Brave leaves the class empty for PiP, so we match by title only
	-- Effects
	float = true,
	pin = true,
	animation = "none",
	-- Your preferred dimensions
	size = "530 300",
	move = "1380 830",
})

hl.window_rule({
	name = "bitwarden-float",
	match = {
		class = "^brave-nngceckbapebfimnlniiiahkandclblb-Default$",
	},
	-- Match exact casing from your hyprctl output
	-- Effects
	float = true,
	center = true,
	pin = true,
	dim_around = true,
	stay_focused = true,
	-- Matching the exact case for Bitwarden
	-- opacity = 0.8 0.8
	-- Set size (important for popups)
	size = "480 700",
})

hl.window_rule({
	name = "spotify-browser-pip",
	match = {
		class = "^brave-browser-nightly$",
		title = ".* • .*",
	},
	-- Effects
	float = true,
	pin = true,
	animation = "none",
	-- Dimensions & positioning
	size = "340 340",
	move = "1570 850",
})

hl.window_rule({
	name = "browser-login-popups",
	match = {
		class = "^(brave-browser|Brave-browser)$",
		title = "^(Sign in|Log in|Authorize|Authentication|Connect|OAuth).*$",
	},
	-- Match popups originating from Brave (or any browser)
	-- Alternatively, target popups using initialTitle or role if set
	-- match:popin = true
	-- Layout & Float
	float = true,
	center = true,
	stay_focused = true,
	dim_around = true,
	-- Compact dimensions for popup windows
	size = "500 700",
})

hl.window_rule({
	match = {
		class = "firefox",
	},
	no_blur = true,
})

-- windowrule = opacity 0.6 0.6, match:float true
hl.window_rule({
	match = {
		class = "kitty",
	},
	opacity = "0.8 0.8",
})

-- bluetui & impala
hl.window_rule({
	match = {
		class = "^(impala-float|bluetui-float)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^(impala-float|bluetui-float)$",
	},
	size = "900 600",
})

hl.window_rule({
	match = {
		class = "^(impala-float|bluetui-float)$",
	},
	center = true,
})

hl.window_rule({
	match = {
		class = "^(impala-float|bluetui-float)$",
	},
	pin = true,
})

hl.window_rule({
	match = {
		class = "^(impala-float|bluetui-float)$",
	},
	dim_around = true,
})

hl.window_rule({
	match = {
		class = "^(impala-float|bluetui-float)$",
	},
	stay_focused = true,
})

hl.window_rule({
	match = {
		class = "^(impala-float|bluetui-float)$",
	},
	opacity = "0.8 0.8",
})

-- Volume Control & File Pickers
hl.window_rule({
	match = {
		class = "^(org.pulseaudio.pavucontrol|xdg-desktop-portal-gtk)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^(org.pulseaudio.pavucontrol|xdg-desktop-portal-gtk)$",
	},
	size = "900 600",
})

hl.window_rule({
	match = {
		class = "^(org.pulseaudio.pavucontrol|xdg-desktop-portal-gtk)$",
	},
	center = true,
})

hl.window_rule({
	match = {
		class = "^(org.pulseaudio.pavucontrol|xdg-desktop-portal-gtk)$",
	},
	pin = true,
})

hl.window_rule({
	match = {
		class = "^(org.pulseaudio.pavucontrol|xdg-desktop-portal-gtk)$",
	},
	dim_around = true,
})

hl.window_rule({
	match = {
		class = "^(org.pulseaudio.pavucontrol|xdg-desktop-portal-gtk)$",
	},
	stay_focused = true,
})

-- Polkit Authentication Agent
hl.window_rule({
	match = {
		class = "^(polkit-gnome-authentication-agent-1|hyprpolkitagent)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^(polkit-gnome-authentication-agent-1|hyprpolkitagent)$",
	},
	center = true,
})

hl.window_rule({
	match = {
		class = "^(polkit-gnome-authentication-agent-1|hyprpolkitagent)$",
	},
	pin = true,
})

hl.window_rule({
	match = {
		class = "^(polkit-gnome-authentication-agent-1|hyprpolkitagent)$",
	},
	stay_focused = true,
})

-- Full Bluetooth Manager
hl.window_rule({
	match = {
		class = "^(blueman-manager)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^(blueman-manager)$",
	},
	size = "800 500",
})

hl.window_rule({
	match = {
		class = "^(blueman-manager)$",
	},
	center = true,
})

-- Catch common dialog titles
hl.window_rule({
	match = {
		title = "^(Confirm to replace files|File Operation Progress|Authentication Required)$",
	},
	float = true,
})

--zoom
-- Zoom Workplace rules
hl.window_rule({
	name = "zoom-main-tile",
	match = {
		class = "^(zoom)$",
		title = "^(Zoom Meeting|Zoom Workplace)$",
	},
	float = false,
})

hl.window_rule({
	name = "zoom-popups-float",
	match = {
		class = "^(zoom)$",
		title = "^(Settings|Participants|Chat|Meeting Information|Breakout Rooms|Select a window)$",
	},
	float = true,
	center = true,
})

hl.window_rule({
	name = "termius-float",
	match = { class = "^(Termius|termius-app)$" },
	float = true,
	size = { 1200, 800 },
	center = true,
})

hl.config({
	group = {
		col = {
			border_active = "rgba(89b4faee)", -- Active group border (Catppuccin Blue)
			border_inactive = "rgba(313244aa)", -- Inactive group border
		},
		groupbar = {
			enabled = true, -- Set false if you don't want the top tab bar visible
			font_size = 10,
			gradients = false,
			col = {
				active = "rgba(89b4faee)",
				inactive = "rgba(313244aa)",
			},
			text_color = "rgba(cdd6f4ff)",
		},
	},
})

hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
	hl.exec_cmd("waybar")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("swayosd-server")
	hl.exec_cmd("swaync")
	hl.exec_cmd("swww-daemon || awww-daemon")
	hl.exec_cmd("sleep 0.5 && (swww restore || awww restore)")
	hl.exec_cmd("wl-paste --type text --watch cliphist -max-items 500 store")
	hl.exec_cmd("wl-paste --type image --watch cliphist -max-items 100 store")
end)
